import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: [
      "test/core/surface-adapter.test.ts",
      "test/agent-eval/case.test.ts",
      "test/agent-eval/list-detail-complete-fixture.test.ts",
      "test/agent-eval/local-http-runner.test.ts",
      "test/agent-eval/outcome.test.ts",
      "test/agent-eval/preview-confirm-fixture.test.ts",
      "test/agent-eval/probe-runner.test.ts",
      "test/agent-eval/submit-message-fixture.test.ts",
      "test/agent-eval/trace.test.ts",
      "test/module-boundaries.test.ts",
      "test/package-scripts.test.ts",
      "test/public-api.test.ts",
      "test/core/agent-blocks.test.ts",
      "test/core/public-api.test.ts",
      "test/core/action-proof.test.ts",
      "test/core/contracts.test.ts",
      "test/core/content-actions.test.ts",
      "test/core/field-schema.test.ts",
      "test/core/input-schema.test.ts",
      "test/core/json-body.test.ts",
      "test/core/markdown-body.test.ts",
      "test/core/markdown-renderer.test.ts",
      "test/core/negotiate.test.ts",
      "test/core/serialize.test.ts",
      "test/core/semantic-slots.test.ts",
      "test/elements/model.test.ts",
      "test/elements/headless-host-integration.test.ts",
      "test/server/adapter-shared.test.ts",
      "test/server/agent-consumption-contract.test.ts",
      "test/server/auto-dependencies.test.ts",
      "test/server/browser-shell.test.ts",
      "test/server/host-adapter-shared.test.ts",
      "test/server/host-flow-shared.test.ts",
      "test/server/public-api.test.ts",
      "test/server/request-helpers.test.ts",
      "test/server/result-content-type-session.test.ts",
      "test/server/router.test.ts",
      "test/server/runtime-assets.test.ts",
      "test/server/runtime-json-contract-mode.test.ts",
      "test/server/runtime-action-proof.test.ts",
      "test/shared/sse-render-semantics.test.ts",
      "test/web/headless.test.ts",
      "create-mdan/test/cli.test.ts",
      "create-mdan/test/scaffold.test.ts"
    ],
    coverage: {
      provider: "v8",
      include: [
        "src/surface/adapter.ts",
        "src/content/agent-blocks.ts",
        "src/server/errors.ts",
        "src/protocol/input/input-schema.ts",
        "src/server/json-body.ts",
        "src/content/markdown-body.ts",
        "src/content/markdown-renderer.ts",
        "src/protocol/negotiate.ts",
        "src/content/serialize.ts",
        "src/content/semantic-slots.ts",
        "src/server/adapter-shared.ts",
        "src/server/bun.ts",
        "src/server/content-type.ts",
        "src/server/result.ts",
        "src/server/router.ts",
        "src/server/runtime.ts",
        "src/server/session.ts",
        "src/surface/render-semantics.ts",
        "src/server/sse.ts"
      ],
      thresholds: {
        lines: 75,
        branches: 65,
        functions: 75
      }
    }
  }
});
